#!/bin/zsh
# load the target module dir, the $mod_dir/@init file will be sourced, the other file will load as autoload functions
ARK_MOD=()
function @load() {
    local m=$1
    [[ -d $m ]] || return 0
    [[ $ARK_MOD[(r)$m] ]] && return 0

    # 1. source @init first
    [[ -f $m/@init ]] && source $m/@init
    # 2. add autoload functions
    #TESTME: $fpath contains space
    [[ -z $fpath[(r)$m] ]] && fpath=("$m" $fpath) && autoload -- $m/[^@]*(N:t) > /dev/null
}
ARK=$0:h
@load $ARK/docs
@load $ARK/date
@load $ARK/cmds

#--------------------------------------------
#  AGENT FUNCTIONS
#--------------------------------------------
# @require: jq openssl
function bitrue.spot.config.save() {
@doc "
save bitrue agent config
--user      :
--spot-ak   : spot API ak
--spot-sk   : spot API sk
--out       : output dir
"
    zparseopts -A opts -D -E -- \
        -user:=opts     \
        -spot-ak:=opts  \
        -spot-sk:=opts  \
        -out:=opts
    # save to
    local out=$opts[--out]
    local user=$opts[--user]
    local spot_sk=$opts[--spot-sk]
    local spot_ak=$opts[--spot-ak]

    [[ -f $out ]] && error "the agent '$out' existed"

    local prefix=BITRUE
    local template="\
# Bitrue SPOT API SK
BITRUE_API_SPOT_AK=$spot_ak

# Bitrue SPOT API AK
BITRUE_API_SPOT_SK=$spot_sk
"
    print -n "${(e)template}" > $out
    chmod 600 $out
}


function bitrue.spot.api.trade() {
@doc "
\$1:    market
return: [(market,),...]
"
    local market=$1
    local resp=$(bitrue.http.get api/v2/myTrades recvWindow 5000 symbol "${(U)market}")
    [[ $resp == '[]' ]] && return
    <<< $resp
    #| jq -r '.[] | [.id, .time, .symbol, .price, .qty, .isBuyer] | @tsv'
}

function bitrue.http.get() {
    local p=$1
    [[ -n $p ]] && shift
    params=$(bitrue.api.params "$argv[@]" )
    [[ -n $params ]] && params="?$params"

    local url="${BITRUE_SPOT_API}/$p$params"
    curl -s \
         -H "X-MBX-APIKEY: $BITRUE_API_SPOT_AK " \
         -X GET "$url"
}

function bitrue.time {
    curl -s ${BITRUE_SPOT_API}/api/v1/time | jq .serverTime
}

function bitrue.api.price() {
    local symbol=${1:=btcusdt}
    local ammount=${2:=1}
    local r=$(curl -s "${BITRUE_SPOT_API}/api/v1/ticker/price?symbol=${(U)symbol}" | jq -r .price)
    [[ $r == null ]] && print "0" && return
    expr="x=(${(q)r}*$ammount)/1; if(x<1) print 0; x"
    <<< $expr | bc -l
}

function bitrue.spot.api.order() {
    local market=${1}
    local resp=$(bitrue.http.get api/v1/order recvWindow 5000 symbol "${(U)market}")
    <<< $resp
}



#---------------------------------
#
#             A.R.K
#
#---------------------------------
ARK_HOME=~/.ark
ARK_AGENT=
ARK_AGENT_ID=
ARK_AGENT_UID=
ARK_AGENT_SUPPORTED=(bitrue.spot okx.spot) # supported agent type



typeset -A ARK_PRICE_SPOT_BITRUE
typeset -A ARK_ACCOUNT_BITRUE
typeset -U ARK_ACCOUNT_BITRUE_IDX

ARK_ACCOUNT_BITRUE_IDX=(FTM ALGO ACE)

function ark.state.reset() {
    ARK_ACCOUNT_BITRUE=()
    ARK_ACCOUNT_BITRUE_IDX=()
    ARK_PRICE_SPOT_BITRUE=()
}

function ark.sync() {
    ark.price.sync
    # update price
    local time=$(bitrue.time)
    local bitrue=("${(@f)$(bitrue.spot.price.usdt)}")
    for p in $bitrue; do
        xs=(${=p})
        # last | high | low
        ark.state.price_put $xs[1] $xs[2] $xs[3]
    done

    # update account
    ark.bitrue.account
}

function ark.state.price_put() {
    local id=$1
    local last=$2
    local high=$3
    local low=$4
    ARK_PRICE_SPOT_BITRUE[$id]=$last
}

# $1 : market or id
# $2 : total
# $3 : free
# $4 : lock
function ark.state.account_put() {
    local id=$1
    local total=$2
    local lock=$3
    local free=$4
    ARK_ACCOUNT_BITRUE[$id]=$total
}

# $1: id (BTC ftm)
function ark.state.account_get() {
    local id=$1
    local xs=$ARK_ACCOUNT_BITRUE[${(U)id}]
    print -n $xs
}

function ark.state.price_get() {
    local id=$1
    [[ $id == USDT ]] && print -n 1
    print -n $ARK_PRICE_SPOT_BITRUE[${(U)id}USDT]
}

function ark.bitrue.account() {
    local assets=("${(f@)$(bitrue.api.account)}")
    local sum=()
    local ulock ufree
    # market | locked | free | total
    for x in $assets; do
        xs=(${=x})
        id=$xs[1]
        price=$(ark.state.price_get $id)
        [[ -z $price ]] && price=0
        sum+="$price*$xs[4]"
        ark.state.account_put $id $xs[4] $xs[3] $xs[2]
        [[ $id == USDT ]] && {
            ulock=$xs[3]
            ufree=$xs[2]
        }
    done

    #print -l $sum
    local SUM=$(print -n "scale=2; (${(j:+:)sum})" | bc -l)
    print "total:$SUM free:$ufree lock:$ulock"
}

function ark.main() {
    # ark.sync
    bitrue.api.order.list ftmusdt 30 | ark.calc
    ark.head ftm
}

function ark.head() {
    local idx=(${1})
    for id in $idx; do
        v=$(ark.state.account_get $id)
        print $id $v $(bitrue.api.price ${id}USDT $v)
    done
}

function SUM() {
    print -n "${(j:+:)argv}" | bc -l
}

function SUMU() {
    print -n "scale=2;(${(j:+:)argv})/1" | bc -l
}

function ark.calc() {
    local order="$(<&0)"
    local bu=()
    local bv=()
    local su=()
    local sv=()

    function on_BUY_FILLED() {
        local v=$argv[7]
        local u=$argv[8]
        bu+=$u
        bv+=$v
    }

    function on_SELL_FILLED() {
        local v=$argv[7]
        local u=$argv[8]
        su+=$u
        sv+=$v
    }

    function on_SELL_NEW() {

    }

    function on_SELL_CANCELED() {

    }

    for x in "${(@f)order}"; do
        xs=(${=x})
        side=$xs[3]
        stat=$xs[4]
        on_${side}_${stat} $xs
    done
    print "SELL : $(SUMU $su) $(SUM $sv)"
    print "BUY  : $(SUMU $bu) $(SUM $bv)"
}

(
VERSION=0.0.1

function error() {
    print -u2 $1 && exit ${2:=1}
}
#-----------------------------------------------[ cmd.agent ]
function ark.cmd.agent() {
@doc "
list the agents ark supported
"
    local cmd=$1
    [[ -n $cmd ]] && shift
    ark.cmd.agent.$cmd "$@"
}

function ark.cmd.agent.add() {
@doc "
ark agent add \${agent-id} [bitrue | okx]
"
    local id=$1
    local agent=${(L)2}

    # check params
    [[ -z $id ]] && error "agent id must NOT EMPTY"
    [[ $id =~ '[a-zA-Z]+[a-zA-Z0-9]*' ]] || error "agent id format error"
    [[ -z $agent ]] && error "agent must NOT EMPTY"
    [[ -z $ARK_AGENT_SUPPORTED[(r)$agent] ]] && error "invalidate agent '$agent'"


    # 1. check the agent $user existed?
    local agent_id=${(L)id}@${agent}

    # 2. call agent create functions
    agent_dir=$ARK_HOME/agents
    [[ -d $agent_dir ]] || mkdir -p $agent_dir
    $agent.config.save --out $agent_dir/$agent_id $argv
}

function ark.cmd.agent.list() {
@doc "
list the ark agents
ark agent list \${agent-id}
"
    local agent_dir=$ARK_HOME/agents
    [[ -d $agent_dir ]] || print -u2 "no agents found : '$agent_dir'"

    for a in $agent_dir/*; do
        print $a
    done
}


function ark.cmd.agent.use() {
@doc "
ark agent use \$agent_id
"

}

function ark.cmd.agent.delete() {

}

#-----------------------------------------------[ cmd.order ]
function ark.cmd.order() {
@doc "
ark order
OPTIONS:

COMMANDS:
    list
"
    local cmd=$1
    [[ -n $cmd ]] && shift
    ark.cmd.order.$cmd "$@"
}

function ark.cmd.order.list() {
@doc "
$ ark order list \${agent_id}
List the orders of target agent
OPTIONS:

USEAGE:

"
    local agent_id=$ARK_AGENT

    [[ -z $agent_id ]] && error "Agent is EMPTY"

    local user=${agent_id%@*}
    local agent=${agent_id#*@}

    # 1. Load agent config
    config=$ARK_HOME/agents/$agent_id
    [[ -f $config ]] || error "agent DO NOT EXISTED('$config')"
    source $config

    # 2. Call agent API
    $agent.order.list "$@"
}
#-----------------------------------------------[ cmd.asset ]
function ark.cmd.asset() {

}

#-----------------------------------------------[ cmd.agent ]
function ark.cmd.agent.api() {
    @doc "
        \${agent}.order.list : List all orders
    "
}
#-----------------------------------------------[ cmd.config ]
function ark.cmd.config() {

}


function ark.config.agent.path() {
@doc "
Get the agent config path by agent_id

PARAMS:
    \$1: agent_id   (e.g.: amas)
    \$2: agent_type (e.g.: bitrue)
"
    print -n "$ARK_HOME/agents/${(L)1}@${(L)2}"
}
#-----------------------------------------------[ cmd.test ]
function ark.cmd.test() {
    @doc "test test test..."
}

function ark.cmd.public() {
    @load $ARK/public
    price {1..20}
}

function ark.cmd.load() {
    @load $1
    test.hello
}

function ark.cmd.http() {
    #@load $ARK/http
    #http.debug
    #http.head "a" "111" "b" "222"
    #http.get "$@"
    #http.method GET  "$@"
    #http.method POST "$@"
    #http.get $url h1=1 h2=2 h3=3 -- p1=1 p2=2
    bitrue.spot.api.ping
}

)

ark "$@"
